import streamlit as st
import numpy as np
import pickle
import pandas as pd
from sklearn.preprocessing import StandardScaler
from fpdf import FPDF
import matplotlib.pyplot as plt


class Diabetes():

    def __init__(self):
        pass

    def add_sidebar(self):
        st.header("Details")
        data =pd.read_csv("model/diabetes.csv")
        self.name=st.text_input("Enter your Name : ")
        self.gender=st.selectbox("Gender: ",("Male","Female","Third"))
        if self.gender=="Male":
            st.info("Put Pregnancies value as 0.")
        self.family_status=st.radio("Do any of your family member has been a Diabetic patient: ",["Yes","No"])
        if self.family_status=="Yes":
            self.fname=st.selectbox("Enter how you are related to him/her.",("Father","Mother","GrandFather","GrandMother"))
        self.smoke=st.radio("Smoking status: ",["Yes","No"])
        self.activity=st.selectbox("Duration of physical Exercise per day(min):",("10+","20+","30+","40+","50+","60+","70+","80+","90+"))
        slider_labels=[
            ("Pregnancies","Pregnancies"), ("Glucose(mg/dL)","Glucose"),
            ("BloodPressure(mmHg)","BloodPressure"), ("SkinThickness(mm)","SkinThickness"),
            ("Insulin(mU/ml)","Insulin"), ("BMI","BMI"),
            ("DiabetesPedigreeFunction","DiabetesPedigreeFunction"), ("Age","Age")
        ]
        self.input_data={}
        for label, key in slider_labels:
            if key == "Pregnancies" or key == "Age":
                self.input_data[key] = st.slider(label, int(data[key].min()), int(data[key].max()), int(data[key].mean()))
            else:
                self.input_data[key] = st.slider(label, float(data[key].min()), float(data[key].max()), float(data[key].mean()))


    def get_bar_chart(self):

        scale=StandardScaler()

        categories =['Glucose', 'BloodPressure', 'SkinThickness',
        'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age'
        ]

        mean_values =np.array([120.89, 69.11, 20.54, 79.79, 31.99, 0.47, 33]).reshape(-1,1)

        user_values =np.array([
            self.input_data['Glucose'],
            self.input_data['BloodPressure'],
            self.input_data['SkinThickness'],
            self.input_data['Insulin'],
            self.input_data['BMI'],
            self.input_data['DiabetesPedigreeFunction'],
            self.input_data['Age']
        ]).reshape(-1, 1)

        scaled_mean_values=scale.fit_transform(mean_values).flatten().tolist()
        scaled_user_values=scale.fit_transform(user_values).flatten().tolist()
        data={
            'Category':categories,
            'Mean_Values':scaled_mean_values,
            'User_Input':scaled_user_values
        }
        df = pd.DataFrame(data)

        st.title("Variance Graph")  
        st.bar_chart(df, x='Category', y=['Mean_Values', 'User_Input'])

    def generate_pdf_report(self, status, risk_prob):
        """Generates a PDF report using current session data"""
        pdf = FPDF()
        pdf.add_page()
        

        pdf.set_font("Arial", "B", 20)
        pdf.image("Thumbnail.jpg",10,8,25)
        pdf.cell(200, 10, "Diabetes Risk Assessment Report", ln=True, align="C")
        pdf.ln(10)

        pdf.set_font("Arial","B",16)

        pdf.cell(0,10,"Personal Information",ln=True)
        pdf.set_font("Arial", "", 11)

        pdf.cell(0,8,"Name: "+self.name,ln=True)
        pdf.cell(0,8,f"Gender: {self.gender}")
        if self.family_status=="Yes":
            pdf.cell(0,8,f"Patient's {self.fname} has been an Diabetic Patient.",ln=True)
        pdf.cell(0,8,f"Smoking_Status: {self.smoke}",ln=True)
        pdf.cell(0,8,f"Duration of physical activity(in minutes): {self.activity}",ln=True)

        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, "Clinical Metrics:", ln=True)
        pdf.set_font("Arial", "", 11)
        
        for key, value in self.input_data.items():
            pdf.cell(0, 8, f"{key}: {value}", ln=True)
        
        pdf.ln(10)

        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "Diagnostic Results:", ln=True)
        

        if status == "Diabetic":
            pdf.set_text_color(255, 0, 0)
        else:
            pdf.set_text_color(0, 128, 0)
            
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, f"Status: {status}", ln=True)
        
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Arial", "", 12)
        pdf.cell(0, 10, f"Calculated Risk Probability: {risk_prob:.2f}%", ln=True)
        pdf.ln(3)

        self.save_bar_chart_as_image() # Generate the image
    
        pdf.ln(5)
        pdf.cell(0, 10, "Visual Comparison Chart:", ln=True)
        pdf.image("temp_chart.png", x=10, y=None, w=180)
        pdf.set_font("Arial", "I", 8)
        pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI model and is for informational purposes only. Please consult a healthcare professional.")

        
        # Return the PDF as a byte string
        return pdf.output(dest="S").encode("latin-1")
    
    def save_bar_chart_as_image(self):
        """Generates a static bar chart and saves it as a temporary image"""
        scale = StandardScaler()
        categories = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
        mean_values = np.array([[120.89, 69.11, 20.54, 79.79, 31.99, 0.47, 33]]).T
        user_values = np.array([[self.input_data[k] for k in categories]]).T
        
        s_user = scale.fit_transform(user_values).flatten()
        s_mean = scale.fit_transform(mean_values).flatten()

        fig, ax = plt.subplots(figsize=(8, 5))
        x = np.arange(len(categories))
        width = 0.35

        ax.bar(x - width/2, s_mean, width, label='Mean', color='gray')
        ax.bar(x + width/2, s_user, width, label='Patient', color='blue')

        ax.set_ylabel('Scaled Values')
        ax.set_title('Metric Comparison')
        ax.set_xticks(x)
        ax.set_xticklabels(categories, rotation=45)
        ax.legend()

        plt.tight_layout()
        plt.savefig("temp_chart.png") # Save for PDF inclusion
        plt.close()

    def add_Prediction(self):

        st.subheader("Pediction")
        st.write("The Patient is ")
        model=pickle.load(open('model/diabetes_model.pkl','rb'))
        scaler=pickle.load(open('model/scaler.pkl','rb'))

        input_array=np.array([list(self.input_data.values())])

        input_array_scaled=scaler.transform(input_array)
        prediction=model.predict(input_array_scaled)
        with open("assests/style.css") as f:
            st.markdown("<style>{}</style>".format(f.read()),unsafe_allow_html=True)
        if prediction[0]==1:
            st.write("<span class='Diabetic yes'>Diabetic</span>", unsafe_allow_html=True) 
        else:
            st.write("<span class='Diabetic no'>Non-Diabetic</span>", unsafe_allow_html=True) 
        st.write("Probability of being Diabetic: ",model.predict_proba(input_array_scaled)[0][0]*100,"%")
        st.write("Probability of being non-Diabetic: ",model.predict_proba(input_array_scaled)[0][1]*100,"%")
        st.write("The prediction shown is solely on the basis of dataset provided and should not be used as a substitute for professional diagnosis.")
        status = "Diabetic" if prediction[0] == 1 else "Non-Diabetic"
        prob = model.predict_proba(input_array_scaled)[0][1] * 100
    
        return status, prob